import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HeroSection from '@/components/hero-section'
import Categories from '@/components/categories'
import ProductSection from '@/components/product-section'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Event07</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Categories />
      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

      <ProductSection
        title={"Birthday Decoration"}
        bgGray
      />

      <ProductSection
        title={"Aniversary Decoration"}
      />

    </>
  )
}
